title : I'm Shaohua
tagline: Impossible is nothing
author :
  name : I'm Shaohua
  email : isaac.hu@163.com
  github : imshaohua
  twitter : imshaohua@weibo
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
